spring:
  application:
    name: receiver-http
  cloud.stream:
    kafka:
      binder:
        brokers: localhost:39092
        replicationFactor: 1
firebase:
  config:
    type: "service_account"
    project_id: "zzcheah-saturn"
    private_key_id: ${PRIVATE_KEY_ID:}
    private_key: ${PRIVATE_KEY:}
    client_email: ${CLIENT_EMAIL:}
    client_id: ${CLIENT_ID:}
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: ${CLIENT_X509_CERT_URL:}
  bucket: ${FIREBASE_BUCKET:zzcheah-saturn.appspot.com}





#spring.cloud.stream:
#  function:
#    definition: domainService
#  bindings:
#    domainService-in-0:
#      destination: active.web-domains
#  kafka:
#    bindings:
#      domainService-in-0:
#        consumer:
#          configuration:
#            value:
#              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    binder:
#      brokers:
#        - localhost:9091
#        - localhost:9092