version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
    - saturn-zookeeper-secrets:/etc/zookeeper/secrets
    - saturn-zookeeper-data:/var/lib/zookeeper/data
    - saturn-zookeeper-log:/var/lib/zookeeper/log
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:29092
    volumes:
    - saturn-kafka-secrets:/etc/kafka/secrets
    - saturn-kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  saturn-kafka-secrets:
  saturn-kafka-data:
  saturn-zookeeper-secrets:
  saturn-zookeeper-data:
  saturn-zookeeper-log: